/*
 * ????????1.0 ?????
 * Source: _versions/V11/app.js (V10.4 -> V11)
 * This file is generated by extraction only. Do not hand-edit amounts here.
 */
(function (global) {
  "use strict";
  global.OPERATION_COST_DATA_AUDIT = {
  "metadata": {
    "project": "????????1.0",
    "dataLayerVersion": "current",
    "sourceVersion": "V11",
    "sourceCopiedFrom": "V10.4",
    "sourcePath": "_versions/V11/app.js",
    "sourceSha256": "fdbd55a1e79c6c50037c8e50784491f88c499b48751e367d75cb26f4b5dbce07",
    "extractedAt": "2026-05-18",
    "scope": "???????????????? V1X ???? V2X ??????",
    "runtimeStatus": "???????????_versions/V11 ??? V10.4 ?????",
    "forbiddenSources": [
      "_versions/V11.1",
      "_versions/V11.2"
    ]
  },
  "keyMetrics": {
    "companyAnnualBudgetWan": 24098.86,
    "companyJanMayRawCostWan": 8199.38,
    "homepageJanuaryCostWan": 1471.63,
    "activityJanuaryOperatingCostWan": 1076.37,
    "shijiazhuangJanMayCostWan": 2357.03,
    "liuzhouExhibitionJanMayCostWan": 1125.29,
    "dayeSampleWan": 10.2,
    "factCostDetailRows": 9323,
    "rawCostRows": 5873,
    "allocatedCostRows": 3450,
    "rawCostTotalYuan": 81993796.38,
    "allocatedCostTotalYuan": 21705370.52
  },
  "expectedChecks": {
    "companyAnnualBudgetWan": {
      "actual": 24098.86,
      "expected": 24098.86,
      "tolerance": 0.01,
      "pass": true,
      "diff": 0
    },
    "companyJanMayRawCostWan": {
      "actual": 8199.38,
      "expected": 8199.38,
      "tolerance": 0.05,
      "pass": true,
      "diff": 0
    },
    "homepageJanuaryCostWan": {
      "actual": 1471.63,
      "expected": 1471.63,
      "tolerance": 0.05,
      "pass": true,
      "diff": 0
    },
    "activityJanuaryOperatingCostWan": {
      "actual": 1076.37,
      "expected": 1076.37,
      "tolerance": 0.05,
      "pass": true,
      "diff": 0
    },
    "shijiazhuangJanMayCostWan": {
      "actual": 2357.03,
      "expected": 2357.03,
      "tolerance": 0.05,
      "pass": true,
      "diff": 0
    },
    "liuzhouExhibitionJanMayCostWan": {
      "actual": 1125.29,
      "expected": 1125.29,
      "tolerance": 0.05,
      "pass": true,
      "diff": 0
    },
    "dayeSampleWan": {
      "actual": 10.2,
      "expected": 10.2,
      "tolerance": 0.01,
      "pass": true,
      "diff": 0
    },
    "factCostDetailRows": {
      "actual": 9323,
      "expected": 9323,
      "tolerance": 0,
      "pass": true,
      "diff": 0
    }
  },
  "auditAllV10Data": {
    "errorCount": 0,
    "warningCount": 0,
    "rowCounts": {
      "PROJECTS_V10": 14,
      "VENUES": 40,
      "ACTIVITIES_V10": 254,
      "ACTIVITY_VENUE_USAGE": 575,
      "COST_SUBJECTS": 20,
      "SUPPLIERS": 18,
      "CONTRACTS": 1191,
      "CONTRACT_ITEMS": 2905,
      "QUANTITY_SHEETS": 1997,
      "QUANTITY_LINES": 5448,
      "PROGRESS_SETTLEMENTS": 1301,
      "PROGRESS_SETTLEMENT_LINES": 5448,
      "FINAL_SETTLEMENTS": 617,
      "PAYMENT_RECORDS": 1301,
      "FINANCE_RECORDS": 425,
      "BUDGET_IMPORTS": 84,
      "BUDGET_LINES": 4760,
      "FIXED_COST_POOLS": 810,
      "ALLOCATED_COST_LINES": 3450,
      "UNIT_COST_REFERENCE": 12,
      "FACT_COST_DETAIL": 9323
    },
    "keyAmounts": {
      "raw_cost_total": 81993796.38,
      "allocated_cost_total_activity_only": 21705370.52,
      "settlement_cost_total": 61383427.75,
      "finance_cost_total": 20610368.63,
      "payment_trace_total_not_cost": 46292890.8,
      "final_settlement_trace_total_not_cost": 35797288.53
    },
    "firstIssues": [],
    "issues": []
  },
  "extractionDecision": {
    "scheme": "A",
    "v11ReadsSharedDataThisRound": false,
    "reason": "V10.4/V11 ????????????????????? app.js??????????????????????????? V11.1 ? V20.0 ??? _data/current?"
  }
};
  global.OPERATION_COST_DATA_AUDIT.managementAttentionView = {
    viewName: "VIEW_MANAGEMENT_ATTENTION_PROJECTS",
    file: "_data/current/data-views.js",
    ruleVersion: "management_attention_v11_2026-05-20",
    source: "V11.1 desktop management explanation logic",
    expectedTop5ProjectIds: ["zmd", "sjz", "lzhz", "liuti", "langfang"],
    fields: [
      "rank",
      "project_id",
      "project_short_name",
      "project_name",
      "attention_type",
      "attention_level",
      "management_signal",
      "selection_priority_key",
      "score",
      "total_cost",
      "current_month_cost",
      "annual_budget",
      "sequence_budget",
      "budget_execution_rate",
      "budget_gap",
      "nc_detail_count",
      "activity_count",
      "primary_reason",
      "secondary_reason",
      "tags",
      "rule_version"
    ]
  };
})(typeof window !== "undefined" ? window : globalThis);
